//------------------------------------------------------------------------
// Copyright(c) 2023 Lemon Live Studios.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Lemon-Gain.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Lemon-Gain VST3 (64Bit)"
#else
#define stringFileDescription	"Lemon-Gain VST3"
#endif
#define stringCompanyName		"Lemon Live Studios\0"
#define stringLegalCopyright	"Copyright(c) 2023 Lemon Live Studios."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
